main: me.zombie_striker.qav.Main
version: ${project.version}
api-version: 1.13
name: QualityArmoryVehicles2
softdepend: [QualityArmory, Vault]
depend: [ProtocolLib]
commands:
  QualityArmoryVehicles:
    description: Create images using blocks
    aliases: [qav]
permissions:
  qualityarmoryvehicles.*:
    default: op
    description: Gives access to all QAV perms
    children:
      qualityarmoryvehicles.admin: true
  qualityarmoryvehicles.admin:
    description: Gives access to all QAV admin perms
    default: op
    children:
      qualityarmoryvehicles.unlimitedvehicles: true
      qualityarmoryvehicles.give: true
      qualityarmoryvehicles.spawn: true
      qualityarmoryvehicles.setaspassager: true
      qualityarmoryvehicles.removenearbyvehicles: true
      qualityarmoryvehicles.reload: true
      qualityarmoryvehicles.registerfuel: true
      qualityarmoryvehicles.default: true
      qualityarmoryvehicles.callbackAll: true
      qualityarmoryvehicles.overrideWhitelistCommand: true
      qualityarmoryvehicles.overrideWhitelist: true
      qualityarmoryvehicles.debug: true
      qualityarmoryvehicles.addvehicle: true
      qualityarmoryvehicles.removevehicle: true
      qualityarmoryvehicles.removebugged: true

  qualityarmoryvehicles.default:
    default: true
    description: Default to all QAV perms
    children:
      qualityarmoryvehicles.vehiclelimit.1: true
      qualityarmoryvehicles.callback: true
      qualityarmoryvehicles.craft: true
      qualityarmoryvehicles.shop: true
      qualityarmoryvehicles.garage: true
      qualityarmoryvehicles.use: true
      qualityarmoryvehicles.usevehiclegui: true
      qualityarmoryvehicles.pickupvehicle: true
author:
  Zombie_Striker